name: On Push
on: push

jobs:
  jest:
    defaults:
        run:
            working-directory: ./weather_front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - run: npm run test
        